### ISSUE TITLE
Live Code error: qt graphics toolkit is not available

### ISSUE THREAD

**Issue by m-r-schenk** [joergbrech/Modellbildung-und-Simulation#257] opened 2022-02-16 13:40 UTC
Running code causes an qt error:
error: graphics_toolkit: qt toolkit is not available
error: called from
    graphics_toolkit at line 81 column 5

The error disappears, after rerunning the code.

![image](https://user-images.githubusercontent.com/57954821/154275719-fb67669f-6be4-404c-87bf-cb9734044637.png)

**Comment by PhiSpel** [comment] 2022-02-18 14:28
Change something in Modellbildung-und-Simulation)/.binder/

The clue is somewhere here https://mybinder.readthedocs.io/en/latest/

**Comment by PhiSpel** [comment] 2022-02-18 14:30
Duplicate of #242

**Closed by PhiSpel** 2022-02-18 14:30 UTC
